ddlZbor.Items.Add(new ListItem("Prosím vyberte zbor", "0"));
ddlZbor.Items.Add(new ListItem("Aš", "1"));
ddlZbor.Items.Add(new ListItem("Banská Bystrica", "2"));
ddlZbor.Items.Add(new ListItem("Banská Bystrica - CB", "3"));
ddlZbor.Items.Add(new ListItem("Banská Štiavnica", "4"));
ddlZbor.Items.Add(new ListItem("Bardejov - ECAV", "5"));
ddlZbor.Items.Add(new ListItem("Bernolákovo", "6"));
ddlZbor.Items.Add(new ListItem("Blansko", "7"));
ddlZbor.Items.Add(new ListItem("Bratislava - CB", "10"));
ddlZbor.Items.Add(new ListItem("Bratislava - IBCB", "8"));
ddlZbor.Items.Add(new ListItem("Bratislava - UPeCe", "14"));
ddlZbor.Items.Add(new ListItem("Bratislava City Church (AC)", "9"));
ddlZbor.Items.Add(new ListItem("Bratislava I. - Palisády", "11"));
ddlZbor.Items.Add(new ListItem("Bratislava II. - Podunajské Biskupice", "12"));
ddlZbor.Items.Add(new ListItem("Bratislava III. - Viera", "13"));
ddlZbor.Items.Add(new ListItem("Brniště", "15"));
ddlZbor.Items.Add(new ListItem("Brno", "16"));
ddlZbor.Items.Add(new ListItem("Brno - neslyšící", "17"));
ddlZbor.Items.Add(new ListItem("Broumov", "18"));
ddlZbor.Items.Add(new ListItem("Cheb I.", "19"));
ddlZbor.Items.Add(new ListItem("Cheb II.", "20"));
ddlZbor.Items.Add(new ListItem("Cvikov", "21"));
ddlZbor.Items.Add(new ListItem("Děčín", "24"));
ddlZbor.Items.Add(new ListItem("Hurbanovo", "25"));
ddlZbor.Items.Add(new ListItem("Jablonec nad Nisou", "26"));
ddlZbor.Items.Add(new ListItem("Jelšava", "27"));
ddlZbor.Items.Add(new ListItem("Karlovy Vary", "28"));
ddlZbor.Items.Add(new ListItem("Klenovec", "29"));
ddlZbor.Items.Add(new ListItem("Komárno", "30"));
ddlZbor.Items.Add(new ListItem("Košice", "31"));
ddlZbor.Items.Add(new ListItem("Kraslice", "32"));
ddlZbor.Items.Add(new ListItem("Kroměříž", "33"));
ddlZbor.Items.Add(new ListItem("Kuřim", "34"));
ddlZbor.Items.Add(new ListItem("Levice", "35"));
ddlZbor.Items.Add(new ListItem("Liberec", "36"));
ddlZbor.Items.Add(new ListItem("Liptovský Mikuláš", "37"));
ddlZbor.Items.Add(new ListItem("Litoměřice", "38"));
ddlZbor.Items.Add(new ListItem("Lovosice", "39"));
ddlZbor.Items.Add(new ListItem("Lučenec", "40"));
ddlZbor.Items.Add(new ListItem("Miloslavov", "41"));
ddlZbor.Items.Add(new ListItem("Nesvady", "42"));
ddlZbor.Items.Add(new ListItem("Nové Zámky - Radostná správa", "43"));
ddlZbor.Items.Add(new ListItem("Odense (Dánsko)", "44"));
ddlZbor.Items.Add(new ListItem("Olomouc", "45"));
ddlZbor.Items.Add(new ListItem("Ostrava", "46"));
ddlZbor.Items.Add(new ListItem("Panické Dravce", "47"));
ddlZbor.Items.Add(new ListItem("Pardubice", "48"));
ddlZbor.Items.Add(new ListItem("Plzeň", "49"));
ddlZbor.Items.Add(new ListItem("Poprad", "50"));
ddlZbor.Items.Add(new ListItem("Praha 13", "51"));
ddlZbor.Items.Add(new ListItem("Praha 3 - IBCP", "52"));
ddlZbor.Items.Add(new ListItem("Praha 3 - Vinný kmen", "53"));
ddlZbor.Items.Add(new ListItem("Praha 3 - Vinohrady", "54"));
ddlZbor.Items.Add(new ListItem("Praha 4 - Na Topolce", "55"));
ddlZbor.Items.Add(new ListItem("Praha 6 - ŠVCC", "56"));
ddlZbor.Items.Add(new ListItem("Prešov - ECAV", "57"));
ddlZbor.Items.Add(new ListItem("Příbor", "58"));
ddlZbor.Items.Add(new ListItem("Revúcka Lehota", "59"));
ddlZbor.Items.Add(new ListItem("Ružomberok", "60"));
ddlZbor.Items.Add(new ListItem("Sokolov", "61"));
ddlZbor.Items.Add(new ListItem("Srbsko", "62"));
ddlZbor.Items.Add(new ListItem("Suchdol nad Odrou", "63"));
ddlZbor.Items.Add(new ListItem("Svatá Helena (RO)", "64"));
ddlZbor.Items.Add(new ListItem("Svätý Peter", "65"));
ddlZbor.Items.Add(new ListItem("Tekovské Lužany", "69"));
ddlZbor.Items.Add(new ListItem("Teplice", "70"));
ddlZbor.Items.Add(new ListItem("Teplá", "71"));
ddlZbor.Items.Add(new ListItem("Uherské Hradiště", "72"));
ddlZbor.Items.Add(new ListItem("Vavrišovo", "73"));
ddlZbor.Items.Add(new ListItem("Vikýřovice", "74"));
ddlZbor.Items.Add(new ListItem("Vsetín", "75"));
ddlZbor.Items.Add(new ListItem("Vysoké Mýto", "76"));
ddlZbor.Items.Add(new ListItem("Zlín", "77"));
ddlZbor.Items.Add(new ListItem("České Budějovice", "22"));
ddlZbor.Items.Add(new ListItem("Čjinové", "23"));
ddlZbor.Items.Add(new ListItem("Štôla", "66"));
ddlZbor.Items.Add(new ListItem("Šumperk", "67"));
ddlZbor.Items.Add(new ListItem("Šumperk - Kostel jinak", "68"));
ddlZbor.Items.Add(new ListItem("Žatec", "78"));
ddlZbor.Items.Add(new ListItem("Iný...", "-1"));
