DELETE FROM [dbo].[zbor];
GO
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (1, N'Aš');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (2, N'Banská Bystrica');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (3, N'Banská Bystrica - CB');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (4, N'Banská Štiavnica');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (5, N'Bardejov - ECAV');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (6, N'Bernolákovo');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (7, N'Blansko');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (8, N'Bratislava - IBCB');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (9, N'Bratislava City Church (AC)');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (10, N'Bratislava - CB');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (11, N'Bratislava I. - Palisády');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (12, N'Bratislava II. - Podunajské Biskupice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (13, N'Bratislava III. - Viera');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (14, N'Bratislava - UPeCe');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (15, N'Brniště');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (16, N'Brno');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (17, N'Brno - neslyšící');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (18, N'Broumov');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (19, N'Cheb I.');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (20, N'Cheb II.');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (21, N'Cvikov');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (22, N'České Budějovice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (23, N'Čjinové');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (24, N'Děčín');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (25, N'Hurbanovo');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (26, N'Jablonec nad Nisou');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (27, N'Jelšava');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (28, N'Karlovy Vary');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (29, N'Klenovec');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (30, N'Komárno');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (31, N'Košice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (32, N'Kraslice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (33, N'Kroměříž');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (34, N'Kuřim');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (35, N'Levice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (36, N'Liberec');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (37, N'Liptovský Mikuláš');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (38, N'Litoměřice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (39, N'Lovosice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (40, N'Lučenec');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (41, N'Miloslavov');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (42, N'Nesvady');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (43, N'Nové Zámky - Radostná správa');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (44, N'Odense (Dánsko)');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (45, N'Olomouc');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (46, N'Ostrava');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (47, N'Panické Dravce');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (48, N'Pardubice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (49, N'Plzeň');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (50, N'Poprad');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (51, N'Praha 13');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (52, N'Praha 3 - IBCP');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (53, N'Praha 3 - Vinný kmen');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (54, N'Praha 3 - Vinohrady');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (55, N'Praha 4 - Na Topolce');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (56, N'Praha 6 - ŠVCC');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (57, N'Prešov - ECAV');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (58, N'Příbor');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (59, N'Revúcka Lehota');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (60, N'Ružomberok');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (61, N'Sokolov');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (62, N'Srbsko');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (63, N'Suchdol nad Odrou');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (64, N'Svatá Helena (RO)');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (65, N'Svätý Peter');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (66, N'Štôla');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (67, N'Šumperk');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (68, N'Šumperk - Kostel jinak');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (69, N'Tekovské Lužany');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (70, N'Teplice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (71, N'Teplá');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (72, N'Uherské Hradiště');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (73, N'Vavrišovo');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (74, N'Vikýřovice');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (75, N'Vsetín');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (76, N'Vysoké Mýto');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (77, N'Zlín');
INSERT INTO [dbo].[zbor] ([id], [name]) VALUES (78, N'Žatec');
GO
